177492288 report by asn
brianlong/www.validators.app pull request #106
Opened 2021-05-24 08:08 UTC by maciejkocylapc

#### What's this PR do?
Add sort by asn option to data center page

#### How should this be manually tested?
There should be separate tab in data centers page for sorting by ASN

#### What are the relevant tickets?
https://www.pivotaltracker.com/story/show/177492288

#### Task completed checklist:
- [Y] Is there appropriate test coverage?
- [Y] Did I take into consideration possible security vulnerabilities?
- [Y] Are the controllers secure?
- [Y] Was every important matter documented?

#### Things to watch out for
- [N] Does this PR have any migrations?
- [N] Does this PR add new dependencies?

2021-05-26 11:21 UTC, radek-polcode requested changes
Please add new lines at the end of the files where needed.
Do we want to add epoch_wall_clocks in schema.rb?

2021-05-26 14:54 UTC, kbiala requested changes

2021-05-26 14:54 UTC, kbiala commented on app/views/data_centers/index.html.erb
> +              class: "btn #{[nil, 'data_center'].include?(@sort_by) ? 'btn-primary' : 'btn-outline-primary'}", \
Please do not use ```btn-outline-primary``` class, it's not fully styled in app (has some bootstrap left-overs that we don't want). Use ```btn-secondary``` instead.

2021-05-26 14:54 UTC, kbiala commented on app/views/data_centers/index.html.erb
> +              class: "btn #{@sort_by == 'asn' ? 'btn-primary' : 'btn-outline-primary'}", \
Same as above.

2021-05-26 14:54 UTC, kbiala commented on app/views/data_centers/index.html.erb
> +              class: "btn #{[nil, 'data_center'].include?(@sort_by) ? 'btn-primary' : 'btn-outline-primary'}", \
Also, please add ```mr-1``` class to all buttons

2021-05-28 13:43 UTC, radek-polcode requested changes
add missing new lines as well

2021-05-28 13:43 UTC, radek-polcode commented on app/views/asns/show.html.erb
> +            <% @data_centers.uniq.each do |dc| %>
`uniq` can be moved to controller I think.

2021-05-28 13:43 UTC, radek-polcode commented on app/views/validators/_as_row.html.erb
> +      <% if this_validator && this_validator.avatar_url %>
This can be moved to helper.

2021-05-28 13:43 UTC, radek-polcode commented on app/views/validators/_as_row.html.erb
> +    <% if Ip.where(address: score.ip_address).first %>
Is it possible to pass this as a variable to this partial?

2021-05-28 13:43 UTC, radek-polcode commented on app/views/validators/_as_row.html.erb
> +      <%= Ip.where(address: score.ip_address).first&.data_center_host %>
Repetition

2021-05-28 13:43 UTC, radek-polcode commented on app/views/validators/_as_row.html.erb
> +      (<%= number_to_percentage((score.active_stake / @total_stake.to_f)*100.0, precision: 2) %>)
`(score.active_stake / @total_stake.to_f)*100.0` could be moved to the helper or maybe to a model if possible.

2021-05-28 14:07 UTC, radek-polcode commented on app/views/data_centers/_asn_list.html.erb
> +      (<%= number_to_percentage((asn_data[:active_stake] / @results[:total_stake].to_f) * 100.0, precision: 2) %>)
This calculation `(asn_data[:active_stake] / @results[:total_stake].to_f) * 100.0` also could be in a helper.

2021-05-28 14:08 UTC, radek-polcode commented on app/views/data_centers/_data_center_list.html.erb
> +      (<%= number_to_percentage((dc_data[:active_stake] / @results[:total_stake].to_f) * 100.0, precision: 2) %>)
`(dc_data[:active_stake] / @results[:total_stake].to_f) * 100.0` could be a helper method

2021-05-31 07:14 UTC, maciejkocylapc commented on app/controllers/asns_controller.rb
> +    @total_stake = ValidatorScoreV1.where(network: asn_params[:network])
we do not need validator here at all

2021-05-31 11:21 UTC, radek-polcode requested changes

2021-05-31 11:21 UTC, radek-polcode commented on app/controllers/asns_controller.rb
>                                .where(data_center_key: @data_centers)
Consider make it a scope.

2021-05-31 11:21 UTC, radek-polcode commented on app/views/validators/_as_row.html.erb
> +      <% if avatar_present?(this_validator) %>
Make all condition a helper method.

2021-05-31 11:32 UTC, radek-polcode commented on test/factories/ips.rb
> +    factory :ip_berlin do
I think you shoul use trait here and below https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#traits

2021-05-31 14:12 UTC, radek-polcode approved these changes

2021-05-31 16:33 UTC, merged