179922946-add-delinquent-filtering-in-data-centers
brianlong/www.validators.app pull request #241
Opened 2021-10-20 09:59 UTC by maciejkocylapc

#### What's this PR do?
add filtering by delinquent and inactive in data centers and asns views

#### How should this be manually tested?
- data center show and asn show pages should have filtering working correctly
- in the index pages (for data centers / asns) delinquent number should be a link to filter

#### What are the relevant tickets?
https://www.pivotaltracker.com/story/show/179922946

#### Task completed checklist:
- [] Is there appropriate test coverage?
- [] Did I take into consideration possible security vulnerabilities?
- [] Are the controllers secure?
- [] Was every important matter documented?

#### Things to watch out for
- [N] Does this PR have any migrations?
- [N] Does this PR add new dependencies?

2021-10-20 11:32 UTC, kbiala commented on app/views/data_centers/_data_center_list.html.erb
> +          data_center_url(network: params[:network], key: dc_key.gsub('/', '-slash-'), filter_by: :delinquent) %>
Too small indentation

2021-10-21 14:47 UTC, radek-polcode commented on test/models/validator_score_v1_test.rb
> +    refute ValidatorScoreV1.filtered_by(:inactive).first.validator.is_active
```suggestion
    refute ValidatorScoreV1.filtered_by(:inactive).all? { |score| score.validator.is_active }
```

2021-10-21 14:50 UTC, radek-polcode commented on test/models/validator_score_v1_test.rb
> +    assert ValidatorScoreV1.filtered_by(:delinquent).first.delinquent
```suggestion
    assert ValidatorScoreV1.filtered_by(:delinquent).all? { |val| val.delinquent }
```

2021-10-21 14:53 UTC, radek-polcode commented on app/models/validator_score_v1.rb
> +      joins(:validator).where('validator.is_active': false)
```suggestion
      select('validator_score_v1s.*, validator.is_active').joins(:validator).where('validator.is_active': false)
```

2021-11-04 15:35 UTC, kbiala requested changes
Filtering on staging server is not working. It shows all validators in ASN, no matter which filter is active. Seems to be working fine for Data Center views.

2021-11-04 15:36 UTC, kbiala requested changes

2021-11-04 15:36 UTC, kbiala commented on app/views/asns/show.html.erb
> +    class: "btn btn-sm btn-secondary mb-4 #{'active' if params[:filter_by] == 'delinquent'}" %>
Please add 'mr-1' class for each button. In the future please try to keep styling consistent with the rest of the page.

2021-11-15 13:12 UTC, kbiala approved these changes

2021-11-15 13:12 UTC, merged