WIP
brianlong/www.validators.app pull request #276
Opened 2021-11-25 17:20 UTC by radek-polcode

#### What's this PR do?
- DESCRIBE THE PURPOSE OF THE PR HERE

#### How should this be manually tested?
- List the testing steps here

#### What are the relevant tickets?
- URL to the PivotalTracker ticket

#### Task completed checklist:
- [] Is there appropriate test coverage?
- [] Did I take into consideration possible security vulnerabilities?
- [] Are the controllers secure?
- [] Was every important matter documented?

#### Things to watch out for
- [N] Does this PR have any migrations?
- [N] Does this PR add new dependencies?

2021-12-01 13:01 UTC, maciejkocylapc requested changes

2021-12-01 13:02 UTC, maciejkocylapc commented
I would also exchange places of the buttons hide/show private and reset filters

2021-12-01 13:53 UTC, maciejkocylapc approved these changes

2021-12-02 13:04 UTC, kbiala approved these changes

2021-12-07 14:09 UTC, merged