180359150 tweak stake pool display
brianlong/www.validators.app pull request #279
Opened 2021-12-01 13:39 UTC by kbiala

#### What's this PR do?
- Tweak styling of stake accounts page and some other small elements, like buttons and pagination.

#### How should this be manually tested?
- Go to /stake_accounts page and review in browser.

#### What are the relevant tickets?
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/n/projects/2177859/stories/180359150)

#### Task completed checklist:
- [] Is there appropriate test coverage?
- [] Did I take into consideration possible security vulnerabilities?
- [] Are the controllers secure?
- [] Was every important matter documented?

#### Things to watch out for
- [N] Does this PR have any migrations?
- [N] Does this PR add new dependencies?

2021-12-01 16:05 UTC, radek-polcode requested changes
Sol Prices not working correctly, `Uncaught TypeError: Cannot read properties of null (reading 'replace')`

You did a lot of stuff out of the scope of the story, please avoid that.

2021-12-01 16:05 UTC, radek-polcode commented on app/views/data_centers/data_center.html.erb
> +      class: 'btn btn-sm btn-tertiary mr-1 mb-4' %>
Same as above. Also you haven't changed button in asns view.

2021-12-01 16:12 UTC, kbiala commented
@radek-polcode The error you mentioned is not related to this story and it's also thrown on production. The sol prices view is working now.
Things you mentioned were related to this story - changes on other views were necessary to keep consistency,

2021-12-02 12:45 UTC, merged

2021-12-02 12:46 UTC, maciejkocylapc approved these changes