180571019_add_task_to_capistrano
brianlong/www.validators.app pull request #287
Opened 2021-12-09 14:14 UTC by radek-polcode

#### What's this PR do?
- Add task to deploy.rb to update fees

#### How should this be manually tested?
- 

#### What are the relevant tickets?
- https://www.pivotaltracker.com/story/show/180571019

#### Task completed checklist:
- [] Is there appropriate test coverage?
- [] Did I take into consideration possible security vulnerabilities?
- [] Are the controllers secure?
- [] Was every important matter documented?

#### Things to watch out for
- [N] Does this PR have any migrations?
- [N] Does this PR add new dependencies?

2021-12-13 08:09 UTC, maciejkocylapc approved these changes

2021-12-13 13:21 UTC, kbiala requested changes

2021-12-13 13:21 UTC, kbiala commented on config/deploy.rb
> +  desc 'Update manager fees to Stake Pools'
You need to execute rake task within app folder - it's not systemctl service, it's rails task. So the correct syntax would be:
````
  desc 'Update manager fees to Stake Pools'
  task :update_fee_in_stake_pools do
    on release_roles([:all]) do
      within release_path do
        with rails_env: fetch(:rails_env) do
          execute :rake, 'update_fee_in_stake_pools:mainnet'
        end
      end
    end
  end
```

2021-12-14 11:25 UTC, kbiala approved these changes

2021-12-14 11:25 UTC, merged