180570785_change_price_format
brianlong/www.validators.app pull request #288
Opened 2021-12-09 17:18 UTC by radek-polcode

#### What's this PR do?
- Uses comma as a delimiterfor thousands + display only two decimal places
- 
#### How should this be manually tested?
- Go to `localhost:3000/stake_accounts` and check how sols in first columns are displayed (they should be delimited by thousands and have 2 decimal places)

#### What are the relevant tickets?
- https://www.pivotaltracker.com/story/show/180570785

#### Task completed checklist:
- [] Is there appropriate test coverage?
- [] Did I take into consideration possible security vulnerabilities?
- [] Are the controllers secure?
- [] Was every important matter documented?

#### Things to watch out for
- [N] Does this PR have any migrations?
- [N] Does this PR add new dependencies?

2021-12-13 08:16 UTC, maciejkocylapc requested changes
There is no delimiter for thousands

2021-12-14 12:02 UTC, kbiala commented on app/models/stake_account.rb
> +    stake_in_sol = (delegated_stake / 1_000_000_000.to_f)
Generally ok, but I'd make it a helper as well, it may be useful in case we want to transform lamports to sols in some other place.

2021-12-15 11:10 UTC, maciejkocylapc commented on test/helpers/application_helper_test.rb
> +    assert_equal "12,341.23", lamports_as_formatted_sol(12341232212414)
You could also test for other formats like nil or string

2021-12-15 12:33 UTC, maciejkocylapc approved these changes

2021-12-15 13:55 UTC, merged