180879195_stake_pools_api
brianlong/www.validators.app pull request #309
Opened 2022-01-14 15:49 UTC by radek-polcode

#### What's this PR do?
- Adds stake-pools api endpoint, updates stake-accounts api endpoint

#### How should this be manually tested?
- List the testing steps here

#### What are the relevant tickets?
- URL to the PivotalTracker ticket

#### Task completed checklist:
- [] Is there appropriate test coverage?
- [] Did I take into consideration possible security vulnerabilities?
- [] Are the controllers secure?
- [] Was every important matter documented?

#### Things to watch out for
- [N] Does this PR have any migrations?
- [N] Does this PR add new dependencies?

2022-01-18 11:54 UTC, maciejkocylapc requested changes

2022-01-18 11:54 UTC, maciejkocylapc commented on app/views/public/api_documentation.html.erb
> +    <pre>curl -H "Token: secret-api-token" 'https://www.validators.app/api/v1/stake-accounts/:network'</pre>
add pages to docs

2022-01-19 09:37 UTC, maciejkocylapc approved these changes

2022-01-19 17:47 UTC, kbiala commented
@radek-polcode Please take a look at conflicts

2022-01-21 12:53 UTC, merged