181204864_assign_correct_geo_data
brianlong/www.validators.app pull request #351
Opened 2022-02-11 15:24 UTC by radek-polcode

#### What's this PR do?
- Create new tables and moves data

#### How should this be manually tested?
- Run migrations
- Run script `rails r script/migrate_from_ips_to_data_centers/copy_data_to_data_centers.rb`
- Check file in `tmp/copy_data_to_data_centers.txt`
- Get one `Ip` and find `ValidatorIp` with the same address, then check `DataCenterHost` and `DataCenter` connected with ValidatorIp, compare with Ip data

#### What are the relevant tickets?
- https://www.pivotaltracker.com/story/show/181204864

#### Task completed checklist:
- [] Is there appropriate test coverage?
- [] Did I take into consideration possible security vulnerabilities?
- [] Are the controllers secure?
- [] Was every important matter documented?

#### Things to watch out for
- [N] Does this PR have any migrations?
- [N] Does this PR add new dependencies?

2022-02-23 10:17 UTC, maciejkocylapc requested changes
Script for appending geo_ip data is not updated, so all new ips will be added in the old way.

2022-02-23 10:17 UTC, maciejkocylapc commented on script/migrate_from_ips_to_data_centers/copy_data_to_data_centers.rb
> +    #               ip_override: #{ip_override.id}.\n" unless data_center
are these comments useful ?

2022-02-23 10:17 UTC, maciejkocylapc commented on script/migrate_from_ips_to_data_centers/copy_data_to_data_centers.rb
> +Ip.find_in_batches do |batch|
I would find only IP's that has no corresponding ValidatorIp, just in case we have to run this twice or something brakes.

2022-02-23 10:17 UTC, maciejkocylapc commented on test/models/data_center_test.rb
> +  # test "the truth" do
You could test `to_builder` and `assign_data_center_key` methods

2022-02-23 12:55 UTC, radek-polcode commented
> Script for appending geo_ip data is not updated, so all new ips will be added in the old way.

I am working on it in a separate branch, baby steps

2022-02-24 09:55 UTC, maciejkocylapc approved these changes

2022-03-03 11:43 UTC, merged