182036856 vote accounts is active
brianlong/www.validators.app pull request #434
Opened 2022-05-09 13:19 UTC by maciejkocylapc

#### What's this PR do?
- add is_active flag for vote_accounts and set it in VoteAccountDetailsService

#### How should this be manually tested?
- run tests
- run migrations
- run gather_vote_account_details_daemon.rb
- check if there are accounts with is_active flag set to false

#### What are the relevant tickets?
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/182036856)
- https://www.pivotaltracker.com/story/show/182072088

#### Task completed checklist:
- [] Is there appropriate test coverage?
- [] Did I take into consideration possible security vulnerabilities?
- [] Are the controllers secure?
- [] Was every important matter documented?

#### Things to watch out for
- [Y] Does this PR have any migrations?
- [N] Does this PR add new dependencies?

2022-05-09 15:49 UTC, radek-polcode requested changes

2022-05-09 15:51 UTC, radek-polcode commented on app/services/gatherers/vote_account_details_service.rb
> +          if vacc.update(
You should check here if the values from solana are different than what we already have nad based on that update or not the record

2022-05-10 10:08 UTC, maciejkocylapc commented on app/models/vote_account.rb
> +    self.save(touch: false)
we never want to change timestamps if is_active is changed to false, but I've changed the method name to touch_inactive instead.

2022-05-10 11:48 UTC, radek-polcode requested changes

2022-05-10 11:48 UTC, radek-polcode commented on app/services/gatherers/vote_account_details_service.rb
> +    SCORE_OPTIONS = {
I'd put that to the model and freeze that.

2022-05-10 14:18 UTC, radek-polcode requested changes

2022-05-10 14:18 UTC, radek-polcode commented on app/services/gatherers/vote_account_details_service.rb
> +      vacc.authorized_withdrawer == vote_account_details["authorizedWithdrawer"]
Does this make sense to check `is_active` as well?

2022-05-10 14:18 UTC, radek-polcode commented on test/services/gatherers/vote_account_details_service_test.rb
> +    VoteAccount.delete_all
Is that needed?

2022-05-10 14:18 UTC, radek-polcode commented on test/services/gatherers/vote_account_details_service_test.rb
> +      account: "acc1",
I think this could be initialized in setup so you can use it in all tests, and two attributes below you can update here in test.

2022-05-10 15:38 UTC, radek-polcode requested changes
I think that we also need to test case when solana response is empty, if should_omit is true and if record update fails.

2022-05-11 11:16 UTC, radek-polcode requested changes

2022-05-11 11:16 UTC, radek-polcode commented on test/services/gatherers/vote_account_details_service_test.rb
> +    @json_response = {
Does this need to be instance variable? Similar in other tests.

2022-05-12 10:25 UTC, kbiala approved these changes

2022-05-12 10:27 UTC, merged