182235395 user watchlist
brianlong/www.validators.app pull request #448
Opened 2022-05-25 10:01 UTC by maciejkocylapc

#### What's this PR do?
- users should be able to add validators to watchlist

#### How should this be manually tested?
- log in
- you should be able to see the eye under the avatars on the main page - it adds validator to watchlist
- to filter by watched validators click the eye on the top of the table (over the avatars column)
- run tests

#### What are the relevant tickets?
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/182235395)

#### Task completed checklist:
- [] Is there appropriate test coverage?
- [] Did I take into consideration possible security vulnerabilities?
- [] Are the controllers secure?
- [] Was every important matter documented?

#### Things to watch out for
- [Y] Does this PR have any migrations?
- [N] Does this PR add new dependencies?

2022-05-31 11:12 UTC, radek-polcode requested changes

2022-06-01 09:05 UTC, radek-polcode commented on test/factories/user_watchlist_elements.rb
> +  factory :user_watchlist_element do
It's a useless factory where everything is nil I think

2022-06-01 11:25 UTC, kbiala requested changes

2022-06-01 11:25 UTC, kbiala commented on app/queries/validator_query.rb
> +                                .joins(:validator_score_v1_for_api)
Fix indentation

2022-06-01 11:25 UTC, kbiala commented on app/queries/validator_query.rb
> +    if user_id
It could have been one line:
if user_id && User.find(user_id)

2022-06-01 11:25 UTC, kbiala commented on db/schema.rb
> -  create_table "ip_overrides", charset: "utf8mb4", collation: "utf8mb4_0900_ai_ci", force: :cascade do |t|
These changes are not related to this task

2022-06-01 11:28 UTC, radek-polcode requested changes

2022-06-01 11:28 UTC, radek-polcode commented on app/controllers/users_controller.rb
> +              else
I think it's still not aligned correctly

2022-06-01 11:28 UTC, radek-polcode commented on app/queries/validator_query.rb
> +    if user_id
```suggestion
    @default_scope = if user_id
```

2022-06-01 11:28 UTC, radek-polcode commented on app/models/validator.rb
> +  has_many :user_watchlist_elements
```suggestion
  has_many :user_watchlist_elements, dependent: :destroy
```

2022-06-01 11:28 UTC, radek-polcode commented on app/models/user.rb
> +  has_many :user_watchlist_elements
```suggestion
  has_many :user_watchlist_elements, dependent: :destroy
```

2022-06-02 10:41 UTC, merged