182556424_replacement_for_get_confirmed_block
brianlong/www.validators.app pull request #516
Opened 2022-07-20 14:07 UTC by radek-polcode

#### What's this PR do?
- Replace get_confirmed_block with get_block

#### How should this be manually tested?
- List the testing steps here

#### What are the relevant tickets?
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/182556424)

#### Task completed checklist:
- [] Is there appropriate test coverage?
- [] Did I take into consideration possible security vulnerabilities?
- [] Are the controllers secure?
- [] Was every important matter documented?

#### Things to watch out for
- [N] Does this PR have any migrations?
- [N] Does this PR add new dependencies?

2022-07-26 17:11 UTC, maciejkocylapc requested changes

2022-07-26 17:11 UTC, maciejkocylapc commented on script/one_time_scripts/back_fill_epoch_data.rb
> +%w[testnet].each do |network|
include mainnet

2022-07-26 17:11 UTC, maciejkocylapc commented on test/scripts/add_current_epoch_script_test.rb
> +    EpochWallClock.delete_all
perhaps a teardown action would be better if this line is required?

2022-08-11 11:12 UTC, kbiala approved these changes

2022-08-11 11:12 UTC, merged