182783470 pipeline blacklist
brianlong/www.validators.app pull request #523
Opened 2022-07-28 10:05 UTC by maciejkocylapc

#### What's this PR do?
- Add blacklist for validators that should be omitted by the pipeline

#### How should this be manually tested?
- run tests
- run gather_rpc_testnet_daemon.rb and see if there's no errors

#### What are the relevant tickets?
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/182783470)

#### Task completed checklist:
- [] Is there appropriate test coverage?
- [] Did I take into consideration possible security vulnerabilities?
- [] Are the controllers secure?
- [] Was every important matter documented?

#### Things to watch out for
- [N] Does this PR have any migrations?
- [N] Does this PR add new dependencies?

2022-07-29 14:33 UTC, radek-polcode requested changes

2022-07-29 14:33 UTC, radek-polcode commented on test/logic/solana_logic_test.rb
> +        ).all
I don't think it's needed

2022-07-29 14:33 UTC, radek-polcode commented on test/logic/solana_logic_test.rb
> +        refute validators.count.positive?
Do you want to check if value is not positive or that the are no records? I'd use or `assert_empty validators`

2022-08-02 11:23 UTC, radek-polcode approved these changes

2022-08-02 14:46 UTC, kbiala requested changes

2022-08-02 14:46 UTC, kbiala commented on config/application.rb
> +    config.validator_blacklist = config_for(:validator_blacklist)
I think a better place for this would be an initializer and a constant, instead of a config. It's not a config option.

2022-08-02 14:46 UTC, kbiala commented on config/credentials.yml.enc
> +t3eNHYkOuNaIo7SelaX9R/fG2q3YkeuytQXKYk5ytDPPAL1vN7stFRprHcGEoZ4v9igJxOGMLQhw7rxwYzU0GfsNT6w1poSCqEZq/IYNIBDHiuJz9Kw3J7TNGHHAQ5Kuw8VHHEkUXSYNr+v9/xhKWO2v9JaG1HL92FxBfuJ/HlBCxwastuf/nOhhqVIonyxa7cGor+Y
Why is this file updated?

2022-08-11 09:58 UTC, merged