183383678 Search for ping things
brianlong/www.validators.app pull request #596
Opened 2022-10-19 12:14 UTC by maciejkocylapc

#### What's this PR do?
- filter ping thing table based on the minimum time 

#### How should this be manually tested?
- run dev/create_test_ping_things.rb to populate ping things
- run tests
- check http://localhost:3000/ping-thing and see if the filter works as expected

#### What are the relevant tickets?
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183383678)

#### Task completed checklist:
- [] Is there appropriate test coverage?
- [] Did I take into consideration possible security vulnerabilities?
- [] Are the controllers secure?
- [] Was every important matter documented?

#### Things to watch out for
- [N] Does this PR have any migrations?
- [N] Does this PR add new dependencies?

2022-10-20 09:13 UTC, kamtarnowski requested changes

2022-10-20 09:13 UTC, kamtarnowski commented on app/javascript/packs/ping_thing/ping_thing_table.vue
> +                    {{ pt.signature.substring(0,6) + "..." + pt.signature.substring(pt.signature.length - 4, pt.signature.length) }}
Please create a method containing that logic.

2022-10-20 09:13 UTC, kamtarnowski commented on app/javascript/packs/ping_thing/ping_thing_table.vue
> +        if(this.ping_things_filtered.length > 0){
If there are none filtered records user will get all of the records instead. Isn't this misleading?

2022-10-20 09:13 UTC, kamtarnowski commented on app/javascript/packs/ping_thing/ping_thing_table.vue
> +        axios.get(ctx.api_url + "?time_filter=" + this.filter_time)
Please add additional params using the object:
```suggestion
        axios.get(
          ctx.api_url,
          { params: { time_filter: this.filter_time }}
        ).then(...)
```

2022-10-20 09:13 UTC, kamtarnowski commented on app/javascript/packs/ping_thing/ping_thing_table.vue
> +             console.log(ctx.ping_things_filtered)
Remove pls.

2022-10-20 09:15 UTC, kamtarnowski commented
As I mentioned above, there is a problem if the filtered records array is blank. See a below:
![screenshot-localhost_3000-2022 10 20-11_07_07](https://user-images.githubusercontent.com/7115768/196908186-624bef01-7bc2-480e-a4e9-533f807a0469.png)
![screenshot-localhost_3000-2022 10 20-11_07_38](https://user-images.githubusercontent.com/7115768/196908206-4512c16f-4f3a-4019-9f4a-9bcbfe3cea34.png)

2022-10-20 11:46 UTC, kamtarnowski commented on app/javascript/packs/ping_thing/ping_thing_table.vue
> +             })
Fix the indentation.

2022-10-20 11:52 UTC, kamtarnowski commented
![screenshot-localhost_3000-2022 10 20-13_34_30](https://user-images.githubusercontent.com/7115768/196940158-8a5e5254-dd18-4b49-949e-3a67903947c8.png)

Could user receive in this scenario any message like "0 records found" or "No Ping Things found"?

One more - could you add the @keyup.enter to the input? https://vuejs.org/guide/essentials/event-handling.html#key-modifiers

2022-10-20 12:06 UTC, maciejkocylapc commented on app/javascript/packs/ping_thing/ping_thing_table.vue
> +             })
it's indented in line with .get

2022-10-20 12:27 UTC, kamtarnowski approved these changes

2022-10-26 09:59 UTC, kbiala approved these changes

2022-10-26 09:59 UTC, merged