183792092 merge leaders with map
brianlong/www.validators.app pull request #675
Opened 2022-11-30 14:34 UTC by kbiala

#### What's this PR do?
- Moves leaders component to map

#### How should this be manually tested?
- On localhost run leaders daemon for selected network (eg. `rails r daemons/leader_stats_mainnet_update_daemon.rb`)
- Go to homepage and check the map

#### What are the relevant tickets?
- [URL to the PivotalTracker ticket
](https://www.pivotaltracker.com/story/show/183792092)

#### Task completed checklist:
- [] Is there appropriate test coverage?
- [] Did I take into consideration possible security vulnerabilities?
- [] Are the controllers secure?
- [] Was every important matter documented?

#### Things to watch out for
- [N] Does this PR have any migrations?
- [N] Does this PR add new dependencies?

2022-12-01 15:39 UTC, kamtarnowski requested changes
Please also remove 
`<%= javascript_pack_tag 'leaders/leaders_stats_component.js' %>`
from home_new.html.erb

2022-12-01 15:39 UTC, kamtarnowski commented on app/javascript/packs/validators/validators_map_leaders.js
> +    props: {
Is there something wrong with the indentation?

2022-12-01 15:39 UTC, kamtarnowski commented on app/views/public/home.html.erb
> +<!--
Can we remove these unused lines of code?

2022-12-01 15:42 UTC, kamtarnowski commented
The code looks pretty good, also the homepage seems much better.

2022-12-06 11:19 UTC, kbiala commented
@kamtarnowski done

2022-12-07 08:15 UTC, kamtarnowski approved these changes

2022-12-07 08:24 UTC, kamtarnowski commented
That is not a blocker, but maybe we could just remove this view - `app/views/public/home_new.html.erb`, to not maintain both similar views. Any reference to `home_new` path would be defined in the routes file.

2022-12-07 12:15 UTC, kbiala commented
> That is not a blocker, but maybe we could just remove this view - `app/views/public/home_new.html.erb`, to not maintain both similar views. Any reference to `home_new` path would be defined in the routes file.

Very bad idea - this view was supposed to be different, to show things that are in progress and pending for acceptance.
Anyway, we probably don't need it at all anymore. But in any case it's completely unrelated to this story.

2022-12-07 12:29 UTC, merged