183882630 validator details vue
brianlong/www.validators.app pull request #683
Opened 2022-12-13 07:52 UTC by maciejkocylapc

#### What's this PR do?
- rewride validator details page to vue

#### How should this be manually tested?
- run tests
- check if page looks similar to production
- check if all the links are working

#### What are the relevant tickets?
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/183882630)

#### Task completed checklist:
- [] Is there appropriate test coverage?
- [] Did I take into consideration possible security vulnerabilities?
- [] Are the controllers secure?
- [] Was every important matter documented?

#### Things to watch out for
- [N] Does this PR have any migrations?
- [N] Does this PR add new dependencies?

2022-12-16 12:04 UTC, kamtarnowski requested changes
Cosmetic changes required.

2022-12-16 12:42 UTC, kamtarnowski requested changes

2022-12-16 12:42 UTC, kamtarnowski commented on app/javascript/packs/validators/validator_details.vue
> +            target="_blank">Delegate on Staking.kiwi</a>
It should point out to the BlazeStake.

2022-12-16 12:56 UTC, kamtarnowski commented
Comparing to master branch, some things have been broken.

1)
![Zrzut ekranu 2022-12-16 o 13 49 14 (3)](https://user-images.githubusercontent.com/7115768/208101921-1b014dec-9594-4726-880a-59ec3bed2310.png)
- Delegate button for BlazeStake
- admin warning button (conditional statement is missing)

2) 
![Zrzut ekranu 2022-12-16 o 13 49 08 (3)](https://user-images.githubusercontent.com/7115768/208102396-136d567e-6b22-4119-8cee-caebfdc47e68.png)
- within diagrams there is no data for x and y axis
- no horizontal lines
- there are rectangles instead of wheels.

2022-12-20 10:04 UTC, kamtarnowski commented
set_continuous_supply_updat
![Zrzut ekranu 2022-12-20 o 11 01 55 (3)](https://user-images.githubusercontent.com/7115768/208640400-1fe2f989-e9a5-4e54-a189-b776d18cd3b0.png)
![Zrzut ekranu 2022-12-20 o 11 02 02 (3)](https://user-images.githubusercontent.com/7115768/208640423-b337d631-37b2-4806-a21a-ca39c0912b54.png)

This detail view is still not valid.

2022-12-28 08:42 UTC, kamtarnowski commented
@maciejkocylapc Still there are problems. Please compare it with master branch:

![Zrzut ekranu 2022-12-28 o 09 16 15](https://user-images.githubusercontent.com/7115768/209780965-068a3315-defd-46c0-bc86-d0a11d28de8a.png)

Master:
![Zrzut ekranu 2022-12-28 o 09 23 29](https://user-images.githubusercontent.com/7115768/209781840-edea46d2-d767-4294-92d7-fc9ab9519fb0.png)

Issues spotted:
* "Skipped Slots History" title missed
* there are rectangles instead of wheels
* no horizontal lines
* no axis description (Dist Behind Leader, Previous X Observations, Percent)
* the range values of x axis are too much detailed, there are too many of them

2022-12-28 16:35 UTC, kbiala requested changes
Some validators are failing with `SyntaxError: Unterminated string in JSON`
eg.
http://localhost:3000/validators/6aHUQzbJfX9cb4G6WfBYu7LWjjvEEXak8LHyX2rz7mPM?locale=en&network=mainnet

2022-12-28 16:35 UTC, kbiala commented on app/javascript/packs/validators/components/block_history_table.js
> +      return n.toLocaleString().replace("&nbsp;", ",")
should be:
```suggestion
      return n.toLocaleString('en-US').replace("&nbsp;", ",")
```

2022-12-28 16:35 UTC, kbiala commented on app/controllers/validators_controller.rb
> +    @validator.name = @validator.name&.gsub(" ", "-space-")
Why are we doing this?
Also, why are we using this method instead of updating API controller?

2022-12-28 16:43 UTC, kbiala requested changes

2022-12-28 16:43 UTC, kbiala commented on app/javascript/packs/validators/components/block_history_table.js
> +              {{ (history.skipped_slot_percent * 100.0) }}%<br />
Same here:
`().toLocaleString('en-US', {maximumFractionDigits: 2})`

2022-12-28 16:43 UTC, kbiala requested changes

2022-12-28 16:43 UTC, kbiala commented on app/javascript/packs/validators/components/block_history_table.js
> +              {{ (block_stats(history).total_slots_skipped / block_stats(history).total_slots * 100.0).toLocaleString(2) }}%
This is not a correct use of options
should be
`.toLocaleString('en-US', {maximumFractionDigits: 2})`

2022-12-28 16:56 UTC, kbiala requested changes

2022-12-28 16:56 UTC, kbiala commented on app/javascript/packs/validators/validator_details.vue
> +        <a :href="'/validators?network=' + validator.network + '&order=' + order + '&refresh=' + refresh + '&page=' + page"
There are a couple of params so I'd extract them to a separate variable, or even full path to a separate method.

2022-12-28 16:56 UTC, kbiala commented on app/javascript/packs/validators/validator_details.vue
> +          <p class="small text-muted toggle-label" v-if="refresh">REFRESH ON</p>
Please remove refresh buttons+logic.

2023-01-10 12:33 UTC, kbiala commented on app/javascript/packs/validators/validator_details.js
> +          // score: JSON.parse(this.$el.attributes.score.value),
Comments to remove

2023-01-10 15:14 UTC, kbiala approved these changes

2023-01-10 15:14 UTC, merged