180722100 - provide searcher on every page
brianlong/www.validators.app pull request #685
Opened 2022-12-13 15:34 UTC by kamtarnowski

#### What's this PR do?
- DESCRIBE THE PURPOSE OF THE PR HERE

#### How should this be manually tested?
- List the testing steps here

#### What are the relevant tickets?
- URL to the PivotalTracker ticket

#### Task completed checklist:
- [] Is there appropriate test coverage?
- [] Did I take into consideration possible security vulnerabilities?
- [] Are the controllers secure?
- [] Was every important matter documented?

#### Things to watch out for
- [N] Does this PR have any migrations?
- [N] Does this PR add new dependencies?

2022-12-28 13:53 UTC, psuchta requested changes
Everything works fine except validator searching from the validator show page
/validators/validator_id
When I want to search for a validator from there, I am redirected to the home page

2022-12-28 13:53 UTC, psuchta commented on app/javascript/packs/navigations/validator_searcher_btn_template.vue
> +        if (this.is_active) {
how about 
```suggestion
        validator_searcher_bar.classList.toggle("active")
```

2022-12-28 13:53 UTC, psuchta commented on app/javascript/packs/navigations/validator_searcher_btn_template.vue
> +        if (this.is_active) {
how about delete ifs and do only 
```suggestion
        validator_searcher_bar.classList.toggle("active")
```

2022-12-28 14:15 UTC, kamtarnowski commented on app/javascript/packs/navigations/validator_searcher_btn_template.vue
> +        if (this.is_active) {
It can work out. Thanks 👍

2022-12-29 16:47 UTC, psuchta approved these changes

2022-12-30 14:27 UTC, kbiala requested changes
Search toggle button is not working on mobiles.

2023-01-03 21:35 UTC, kamtarnowski commented
@kbiala please double check it. I tried using Chrome with iphone resolutions (Devtools). All seems fine.

2023-01-04 19:07 UTC, merged