184112299 - add gross yield
brianlong/www.validators.app pull request #695
Opened 2023-01-02 23:11 UTC by kamtarnowski

#### What's this PR do?
- DESCRIBE THE PURPOSE OF THE PR HERE

#### How should this be manually tested?
- List the testing steps here

#### What are the relevant tickets?
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184112299)

#### Task completed checklist:
- [] Is there appropriate test coverage?
- [] Did I take into consideration possible security vulnerabilities?
- [] Are the controllers secure?
- [] Was every important matter documented?

#### Things to watch out for
- [N] Does this PR have any migrations?
- [N] Does this PR add new dependencies?

2023-01-11 17:19 UTC, kamtarnowski commented on app/logic/solana_requests_logic.rb
> +# frozen_string_literal: true
This methods were copied from SolanaLogic module.

2023-01-11 17:36 UTC, kamtarnowski commented
The test suit got crashed, since:

It seems we have to update the testing credentials. The mainnet_urls ("https://api.rpcpool.com") responds with 403 error, so we should use the "https://api.mainnet-beta.solana.com" instead.

2023-02-21 13:40 UTC, kbiala requested changes

2023-02-21 13:40 UTC, kbiala commented on app/services/create_cluster_stats_service.rb
> +      epochs_average_roi = last_epochs(EPOCHS_TO_CALCULATE).map do |epoch|
Don't we have `last_epochs(EPOCHS_TO_CALCULATE)` assigned to a variable few lines above?

2023-02-21 13:40 UTC, kbiala commented on app/services/create_cluster_stats_service.rb
> +      epochs_annual_roi = (365 / epochs_duration) * epochs_average_roi
I'd leave both values (epoch duration and year duration) in seconds, or use floats.

2023-02-21 13:40 UTC, kbiala commented on app/services/create_cluster_stats_service.rb
> +      epochs_duration = (last_epochs.second.created_at - last_epochs.first.created_at) / 60 / 60 / 24
The variable represents the duration of one epoch, so should be called `epochs_duration`, so we do not confuse it with other places where we operate on 3 epochs.

2023-02-22 10:09 UTC, kbiala requested changes

2023-02-22 10:09 UTC, kbiala commented on app/services/create_cluster_stats_service.rb
> +      return 0 unless epoch_duration && epoch_duration > 0
It should be possible to shorten the condition to `epoch_duration.to_f > 0` or  `epoch_duration.to_i > 0`

2023-02-22 10:09 UTC, kbiala commented on app/services/total_rewards_update_service.rb
> +  def completed_epoch
The same comment about relying on ending_slot value.

2023-02-22 12:14 UTC, kbiala requested changes
ClusterStatsWorker should have some retry limit defined.

2023-02-22 12:14 UTC, kbiala commented on app/services/create_cluster_stats_service.rb
> +      epochs_annual_roi = (1.year.to_i / epoch_duration.to_f) * epoch_average_roi
```suggestion
      epochs_annual_roi = (1.year.to_i / epoch_duration.to_f) * epoch_average_roi.to_f
```

2023-02-22 20:06 UTC, kbiala commented on app/services/create_cluster_stats_service.rb
> +      epochs_annual_roi = (1.year.to_i / epoch_duration.to_f) * epoch_average_roi
This still need to be fixed. After deploying to production initially this value will be nil and will throw errors.

2023-02-23 13:24 UTC, kbiala requested changes

2023-02-23 13:24 UTC, kbiala commented on app/javascript/packs/validators/circulating_supply.vue
> +            <a href="/faq#roi">
Let's move it to the next line

2023-02-23 13:24 UTC, kbiala commented on app/javascript/packs/validators/circulating_supply.vue
>                (Last 3 epochs annualized)
```suggestion
              (Last 3 epochs annualized)
               <a href="/faq#roi">
                 <i class="fa-solid fa-circle-info font-size-xs text-muted ms-1"></i>
               </a>
```

2023-02-23 13:24 UTC, kbiala commented on app/models/commission_history.rb
> +#  network             :string(191)
These changes are not a part of this story.

2023-02-23 13:24 UTC, kbiala commented on app/views/public/faq.en.html.erb
>  <hr />
This `<hr />` should go below the whole section, so `Gross ROI` is in the wrong place

2023-02-23 13:24 UTC, kbiala commented on app/views/public/faq.en.html.erb
> +  (stake_account_rewards + vote_account_rewards / total active stake) * number_of_epochs_in_year
```suggestion
  (stake_account_rewards + vote_account_rewards / total_active_stake) * number_of_epochs_per_year
```

2023-02-23 13:24 UTC, kbiala commented on app/views/public/faq.en.html.erb
> +</p>
```suggestion
<p>
  Where number_of_epochs_per_year is calculated as follows: seconds_in_year / duration_of_last_epoch_in_seconds. This gives the number of epochs in a year assuming all epochs were as long as the last epoch.
</p>
<p class="mb-5">
  And stake_account_rewards and vote_account_rewards are the average reward per epoch based on last 3 epochs.
</p>
```

2023-02-27 09:19 UTC, merged