184237181 fix validator cluster stats
brianlong/www.validators.app pull request #713
Opened 2023-01-24 08:58 UTC by maciejkocylapc

#### What's this PR do?
- make sure ClusterStat record is never nullified

#### How should this be manually tested?
- List the testing steps here

#### What are the relevant tickets?
- URL to the PivotalTracker ticket

#### Task completed checklist:
- [] Is there appropriate test coverage?
- [] Did I take into consideration possible security vulnerabilities?
- [] Are the controllers secure?
- [] Was every important matter documented?

#### Things to watch out for
- [N] Does this PR have any migrations?
- [N] Does this PR add new dependencies?

2023-01-24 20:26 UTC, kbiala approved these changes

2023-01-24 21:23 UTC, kbiala commented
<img width="1451" alt="Zrzut ekranu 2023-01-24 o 22 09 51" src="https://user-images.githubusercontent.com/32059143/214416602-b8de20b4-5324-4602-a9ce-7d83be020de2.png">
<img width="1470" alt="Zrzut ekranu 2023-01-24 o 22 10 34" src="https://user-images.githubusercontent.com/32059143/214416637-1bdd327f-a2d7-4354-b3ce-f4f8db5bf0ea.png">
Still the same issue on staging

2023-01-24 22:05 UTC, kbiala requested changes

2023-01-24 22:05 UTC, kbiala commented on app/services/create_cluster_stats_service.rb
> +      validator_history_stats.total_active_stake if validator_history_stats.total_active_stake
This won't work if total_active_stake equals 0.

2023-01-26 10:37 UTC, psuchta approved these changes

2023-01-26 11:26 UTC, merged