184822722 - fix sol price component
brianlong/www.validators.app pull request #774
Opened 2023-04-03 11:48 UTC by kamtarnowski

#### What's this PR do?
- DESCRIBE THE PURPOSE OF THE PR HERE

#### How should this be manually tested?
- List the testing steps here

#### What are the relevant tickets?
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184822722)

#### Task completed checklist:
- [] Is there appropriate test coverage?
- [] Did I take into consideration possible security vulnerabilities?
- [] Are the controllers secure?
- [] Was every important matter documented?

#### Things to watch out for
- [N] Does this PR have any migrations?
- [N] Does this PR add new dependencies?

2023-04-04 16:32 UTC, kbiala requested changes

2023-04-04 16:43 UTC, kbiala requested changes

2023-04-04 16:43 UTC, kbiala commented on daemons/front_stats_update_daemon.rb
> +@init_sol_price = fetch_db_sol_price
Previous version was correct.

2023-04-11 10:53 UTC, kamtarnowski commented on daemons/front_stats_update_daemon.rb
> +    parsed_response = @coin_gecko_response || @init_sol_price
Fixed. `@init_sol_price` was dropped. Using only `@coin_gecko_response`

2023-04-11 14:57 UTC, merged