184549107 - tweak calculating epoch duration
brianlong/www.validators.app pull request #802
Opened 2023-04-24 07:14 UTC by kamtarnowski

#### What's this PR do?
- DESCRIBE THE PURPOSE OF THE PR HERE

#### How should this be manually tested?
- List the testing steps here

#### What are the relevant tickets?
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184549107)

#### Task completed checklist:
- [] Is there appropriate test coverage?
- [] Did I take into consideration possible security vulnerabilities?
- [] Are the controllers secure?
- [] Was every important matter documented?

#### Things to watch out for
- [N] Does this PR have any migrations?
- [N] Does this PR add new dependencies?

2023-04-26 06:33 UTC, maciejkocylapc requested changes

2023-04-26 13:26 UTC, kamtarnowski commented on app/services/cluster_stats/update_epoch_duration_service.rb
> +      (epochs.last.created_at - epochs.first.created_at) / AVG_EPOCH_SIZE
Ok

2023-04-26 13:29 UTC, kamtarnowski commented on app/views/public/faq.en.html.erb
> +  Where number_of_epochs_per_year is calculated as follows: seconds_in_year / average_duration_from_the_last_five_epochs_in_seconds.
Good catch. Changing it.

2023-04-26 15:39 UTC, kbiala commented on app/views/public/faq.en.html.erb
> +  Where number_of_epochs_per_year is calculated as follows: seconds_in_year / average_duration_from_the_last_five_epochs_in_seconds.
Let's just call it average_epoch_duration in formula.
And add below `average_epoch_duration is based on ` and AVG_EPOCH_SIZE constant.

2023-04-27 07:22 UTC, kamtarnowski commented on app/services/cluster_stats/update_epoch_duration_service.rb
> +      (epochs.last.created_at - epochs.first.created_at) / AVG_EPOCH_SIZE
I reverted changes, since `datetime - datetime` returns a float. `to_f` is redundant in this case.

2023-04-27 13:42 UTC, kbiala requested changes

2023-04-27 13:42 UTC, kbiala commented on app/services/cluster_stats/update_epoch_duration_service.rb
> +    AVG_EPOCH_SIZE = 5
What does this constant represent? It's not epoch size, all the more average epoch size. It's a number of epochs that we pull for calculations, so should be called appropriately, NUMBER_OF_EPOCHS.

2023-04-27 13:42 UTC, kbiala commented on app/services/cluster_stats/update_epoch_duration_service.rb
> +      @epochs ||= EpochWallClock.by_network(network).last(AVG_EPOCH_SIZE)
by_network scope sorts epochs in descending order, so you should take first 5 records, not last. Please check how it used in other places of the app next time.

2023-04-27 13:42 UTC, kbiala commented on app/logic/stake_logic.rb
> +      num_of_epochs = number_of_epochs(p.payload[:network])
You removed using current_epoch and previous_epoch, but left all the related code. Variables, set_epochs method, assign_epochs method. There's still a lot to do in this story.

2023-04-27 13:42 UTC, kbiala commented on app/services/create_cluster_stats_service.rb
> +      epoch_average_roi =
Never break the lines this way. If you want to pull the variable name before block, it should be aligned as below.
```suggestion
      epoch_average_roi = last_epochs.map do |epoch|      
```

2023-04-27 13:42 UTC, kbiala commented on app/services/create_cluster_stats_service.rb
> +        (1.year.to_i / epoch_duration) * epoch_average_roi
Same here. It should be one line.

2023-04-27 13:42 UTC, kbiala commented on app/services/create_cluster_stats_service.rb
> +  end
I can see a lot of changed not related to this story. Please avoid it in the future, especially if the story is big enough without additional refactoring. It makes it harder to find where you made a mistake.

2023-05-02 10:06 UTC, kbiala requested changes
Tests are failing.

2023-05-02 10:06 UTC, kbiala commented on test/services/cluster_stats/update_epoch_duration_service_test.rb
> +      create(:epoch_wall_clock, epoch: 355, created_at: 1.day.ago)
Technically it's not an error, but why not use epochs numbers that actually represent epochs that happen one after another in time (whether 1, 2, 3, 4, 5 or 351, 352, 353, 354, 355, no difference). This is how it works in reality. Skipping numbers might be confusing for someone working on it in the future, for example might suggest that we want to skip some epochs, which it's not true.

2023-05-03 12:20 UTC, kamtarnowski commented
I have addressed all of the raised issues.

2023-05-11 14:42 UTC, kbiala requested changes
Testing on staging showed that epoch average duration is not calculated correctly.
It calculated 163912.0 (1.89 days) for mainnet, 155846.0 (1.8 days) for testnet, and 133338.0 (1.54 days) for pythnet. The gross ROI is also messed up because of incorrect epoch duration.
Last 5 epoch on mainnet (starting from the newest one) lasted for 
2.38 days, 2.38 days, 2.39 days, 2.23 days and 2.31 days. So the average cannot be shorter than 2 days.

2023-05-11 14:42 UTC, kbiala commented on test/services/cluster_stats/update_epoch_duration_service_test.rb
> +      assert_equal 207360.0, cluster_stat.reload.epoch_duration
This is incorrect. Do not write tests that always pass, write tests to detect errors.
You created 6 epochs, every one lasting for about 3 days, and yet average is about 2.4 days. It's not correct. The calculated average should be much closer to ~260000 (3 days), and this is the result when I calculate it manually. There's an error somewhere in your code.

2023-05-11 14:45 UTC, kbiala commented on test/services/cluster_stats/update_epoch_duration_service_test.rb
> +      assert_equal 207360.0, cluster_stat.reload.epoch_duration
And you should also check all other places where you changes some values in tests. Looks like you made a lot of unjustified changes, just to make tests pass.

2023-05-11 14:51 UTC, kbiala commented on app/services/cluster_stats/update_epoch_duration_service.rb
> +      (epochs.first.created_at - epochs.last.created_at) / NUMBER_OF_EPOCHS
Here's an error. If you take 5 epochs, you get 4 time differences.
You should take first 6 epochs in line 27, to divide by 5.

2023-05-11 15:03 UTC, kbiala requested changes

2023-05-11 15:03 UTC, kbiala commented on test/logic/stake_logic/apy_helper_test.rb
> +    create(:cluster_stat, network: @network, epoch_duration: 159521.0)
Please set a realistic epoch duration, so we can actually see if the results make sense. Epochs are never shorter than 2 days.

2023-05-11 15:07 UTC, kbiala commented
There's still an old descript in Stake Pools docs

<img width="1112" alt="Zrzut ekranu 2023-05-11 o 17 05 57" src="https://github.com/brianlong/www.validators.app/assets/32059143/8421d51c-58ff-4b21-8a71-3e40c6c31b1f">

2023-05-11 15:10 UTC, kbiala requested changes

2023-05-12 12:42 UTC, kamtarnowski commented
Testing factories were changed to more realistic (epoch_duration).

The number of epochs, which we are using to calculate epoch duration, has increased to 6, so that there we can utilize 5 values of time differences between epochs.

2023-05-12 13:51 UTC, kamtarnowski commented on test/services/cluster_stats/update_epoch_duration_service_test.rb
> +      assert_equal 180000.0, cluster_stat.reload.epoch_duration
I fixed that and the value is 216000.0 currently.

2023-05-12 13:53 UTC, kamtarnowski commented on test/services/cluster_stats/update_epoch_duration_service_test.rb
> +      create(:epoch_wall_clock, epoch: 307)
I added one more epoch_wall_clock to check whether the calculation takes in proper number of epochs( 6). I will remove it.

2023-05-12 13:55 UTC, kamtarnowski commented on app/services/cluster_stats/update_epoch_duration_service.rb
> +      diff / epochs.size
I thought about that solution at some point, but somehow I didn't apply that...

2023-05-12 13:55 UTC, kamtarnowski commented on app/services/cluster_stats/update_epoch_duration_service.rb
> +      return diff if epochs.size <= 2
I did apply your solution.

2023-05-12 14:37 UTC, kbiala requested changes

2023-05-12 14:37 UTC, kbiala commented on app/services/cluster_stats/update_epoch_duration_service.rb
> +      diffs_between_epochs_amount = epochs.size - 1
If you must create a separate variable, which isn't really needed in this case, at least call it appropriately, eg. diff_between_epochs_sum
And then give diff variable (line 31) more meaning name as well, eg last_epochs_duration

2023-05-15 10:39 UTC, kbiala approved these changes

2023-05-17 10:06 UTC, merged