184371663 validator groups
brianlong/www.validators.app pull request #819
Opened 2023-05-24 10:56 UTC by maciejkocylapc

#### What's this PR do?
- create validator groups
- connect validators using groups based on vote accounts info

#### How should this be manually tested?
- run tests
- test on staging

#### What are the relevant tickets?
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/184371663)

#### Task completed checklist:
- [] Is there appropriate test coverage?
- [] Did I take into consideration possible security vulnerabilities?
- [] Are the controllers secure?
- [] Was every important matter documented?

#### Things to watch out for
- [N] Does this PR have any migrations?
- [N] Does this PR add new dependencies?

2023-05-30 11:40 UTC, kamtarnowski requested changes

2023-05-30 11:40 UTC, kamtarnowski commented on app/services/check_group_assignment_service.rb
> +    return unless @vote_account.authorized_voters
Let's add a newline after this line.

2023-05-31 14:14 UTC, kamtarnowski approved these changes

2023-06-01 08:46 UTC, kamtarnowski commented on app/services/check_group_validator_assignment_service.rb
> +      VoteAccount.where(network: @network).each do |va|
`find_each` can be applied.

2023-06-09 08:55 UTC, kbiala requested changes

2023-06-21 16:20 UTC, merged