186061477-review-commission-changes
brianlong/www.validators.app pull request #858
Opened 2023-09-20 12:18 UTC by maciejkocylapc

#### What's this PR do?
- while adding commission histories from rewards, look for history not only in current epoch, but also in previous ones

#### How should this be manually tested?
- run tests

#### What are the relevant tickets?
- [URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/186061477)

#### Task completed checklist:
- [] Is there appropriate test coverage?
- [] Did I take into consideration possible security vulnerabilities?
- [] Are the controllers secure?
- [] Was every important matter documented?

#### Things to watch out for
- [N] Does this PR have any migrations?
- [N] Does this PR add new dependencies?

2023-09-21 09:52 UTC, kbiala approved these changes

2023-09-21 12:24 UTC, kamtarnowski requested changes

2023-09-21 12:24 UTC, kamtarnowski commented on test/services/track_commission_changes_service_test.rb
> +      assert_equal CommissionHistory.count, 0
```suggestion
      assert_equal 0, CommissionHistory.count
```

2023-09-21 12:24 UTC, kamtarnowski commented on test/services/track_commission_changes_service_test.rb
> +      assert_equal CommissionHistory.count, 2
```suggestion
      assert_equal 2, CommissionHistory.count
```

2023-09-21 12:24 UTC, kamtarnowski commented on test/services/track_commission_changes_service_test.rb
>        assert_equal CommissionHistory.count, 0
```suggestion
      assert_equal 0, CommissionHistory.count
```

2023-09-21 12:24 UTC, kamtarnowski commented on test/services/track_commission_changes_service_test.rb
> +      assert_equal CommissionHistory.count, 0
```suggestion
      assert_equal 0, CommissionHistory.count
```

2023-09-21 12:24 UTC, kamtarnowski commented on test/services/track_commission_changes_service_test.rb
> +      assert_equal CommissionHistory.count, 2
```suggestion
      assert_equal 2, CommissionHistory.count
```

2023-09-21 12:24 UTC, kamtarnowski commented on app/services/track_commission_changes_service.rb
>        network: @network,
```suggestion
      network: @network
```

2023-09-22 07:25 UTC, kamtarnowski approved these changes

2023-09-25 10:00 UTC, kbiala approved these changes

2023-09-25 10:01 UTC, merged