186811096 - remove old validator
brianlong/www.validators.app pull request #936
Opened 2024-01-19 23:12 UTC by kamtarnowski

#### What's this PR do?
- DESCRIBE THE PURPOSE OF THE PR HERE

#### How should this be manually tested?
- List the testing steps here

#### What are the relevant tickets?
[- URL to the PivotalTracker ticket](https://www.pivotaltracker.com/story/show/186811096)

#### Task completed checklist:
- [] Is there appropriate test coverage?
- [] Did I take into consideration possible security vulnerabilities?
- [] Are the controllers secure?
- [] Was every important matter documented?

#### Things to watch out for
- [N] Does this PR have any migrations?
- [N] Does this PR add new dependencies?

2024-01-22 19:08 UTC, kbiala requested changes

2024-01-22 19:08 UTC, kbiala commented on script/one_time_scripts/remove_validator.rb
> +    puts "validator_histories deleted"
The whole point of these messages was to see the progress. This way it makes no sense. Please revert it.

2024-01-22 19:08 UTC, kbiala commented on test/logic/solana_logic_test.rb
> +  test '#validators_info_save updates persisted validators' do
```suggestion
  test '#validators_info_save updates data for existing validators' do
```

2024-01-22 19:08 UTC, kbiala commented on test/logic/solana_logic_test.rb
> +      www_url: 'test_www_url',
To simulate real life example you should create a validator without name, keybase_id, details, avatar etc. These data should be completed after script finishes.

2024-01-23 09:55 UTC, kamtarnowski commented on script/one_time_scripts/remove_validator.rb
> +# raise "invalid network - #{network}" unless NETWORKS.include? network
It was unintentional probably because of doing some tests.

Added account checker.

2024-01-23 12:14 UTC, kbiala approved these changes

2024-01-23 13:00 UTC, merged