181608667 remove destroy all from tests
brianlong/www.validators.app pull request #980
Opened 2024-03-15 12:39 UTC by maciejkocylapc

#### What's this PR do?
- remove destroy_all and delete_all from tests
- remove fixtures

#### How should this be manually tested?
- run bundle install
- run tests

#### What are the relevant tickets?
- URL to the PivotalTracker ticket

#### Task completed checklist:
- [] Is there appropriate test coverage?
- [] Did I take into consideration possible security vulnerabilities?
- [] Are the controllers secure?
- [] Was every important matter documented?

#### Things to watch out for
- [N] Does this PR have any migrations?
- [N] Does this PR add new dependencies?

2024-03-18 12:24 UTC, kamtarnowski requested changes
There is also occurrence of destroy_all in test/queries/validator_query_test.rb regarding Validator class. Please address it as well.

2024-03-18 12:24 UTC, kamtarnowski commented on test/logic/validator_score_v1_logic_test.rb
> +    @batch = create(:batch, network: "testnet")
No need network reference. Testnet is default.

2024-03-18 12:24 UTC, kamtarnowski commented on test/logic/validator_score_v1_logic_test.rb
> +    puts p.code
Let's remove of that.

2024-03-18 12:24 UTC, kamtarnowski commented on test/logic/validator_score_v1_logic_test.rb
> +      network: 'testnet',
Let's address printer issue.

2024-03-25 11:49 UTC, kbiala requested changes

2024-03-25 11:49 UTC, kbiala commented on test/controllers/api/v1/validator_block_histories_controller_test.rb
> +    class ValidatorsControllerTest < ActionDispatch::IntegrationTest
This one should be called ValidatorBlockHistoriesControllerTest

2024-03-25 11:49 UTC, kbiala commented on test/logic/validator_score_v1_logic_test.rb
> +    # create enough records to confirm via logs we don"t have an N+1 query when
```suggestion
    # create enough records to confirm via logs we don't have an N+1 query when
```

2024-03-25 11:49 UTC, kbiala commented on test/test_helper.rb
> +  # def after_teardown
You can remote commented part

2024-03-25 15:06 UTC, merged